### ISSUE TITLE
Wrong Datatype for statistics.storage_size 

### ISSUE THREAD

**Issue by MaaxGr** [nmklotas/GitLabApiClient#203]
Storage Size is Bigger than MAX_INT for my project. Probably "long" would be more suitable. :)

```
Newtonsoft.Json.JsonReaderException: JSON integer 12976194741 is too large or small for an Int32. Path '[8].statistics.storage_size', line 1, position 29848.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMemb
er, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty contai
nerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader rea
der, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMemb
er, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty contai
nerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty contai
nerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at GitLabApiClient.Internal.Http.Serialization.RequestsJsonSerializer.Deserialize[T](String serializeJson)
   at GitLabApiClient.Internal.Http.GitLabApiRequestor.ReadResponse[T](HttpResponseMessage responseMessage)
   at GitLabApiClient.Internal.Http.GitLabApiRequestor.GetWithHeaders[T](String url)
   at GitLabApiClient.Internal.Http.GitLabApiPagedRequestor.GetPagedList[T](String url)
   at GitLabApiClient.ProjectsClient.GetAsync(Action`1 options)
   at GitlabManager.Services.Gitlab.Client.GitlabAccountClientImpl.GetAllProjects() in C:\Users\max\Documents\Development\Projects\Privat\GitlabManager\VSProject\GitlabManager\Services\Gitlab\Client\GitlabAccountClientImpl.cs
:line 38
   at GitlabManager.Services.BusinessLogic.GitlabProjectManager.GetProjectsToUpdate(DbAccount account) in C:\Users\max\Documents\Development\Projects\Privat\GitlabManager\VSProject\GitlabManager\Services\BusinessLogic\GitlabP
rojectManager.cs:line 77
   at GitlabManager.Services.BusinessLogic.GitlabProjectManager.UpdateProjectsForAccount(DbAccount account) in C:\Users\max\Documents\Development\Projects\Privat\GitlabManager\VSProject\GitlabManager\Services\BusinessLogic\Gi
tlabProjectManager.cs:line 36
   at GitlabManager.Model.PageProjectsModel.Init() in C:\Users\max\Documents\Development\Projects\Privat\GitlabManager\VSProject\GitlabManager\Model\PageProjectsModel.cs:line 62
   at GitlabManager.ViewModels.PageProjectsViewModel.Init() in C:\Users\max\Documents\Development\Projects\Privat\GitlabManager\VSProject\GitlabManager\ViewModels\PageProjectsViewModel.cs:line 72
   at GitlabManager.ViewModels.WindowMainViewModel.<>c__DisplayClass13_0.<<set_SelectedPage>b__0>d.MoveNext() in C:\Users\max\Documents\Development\Projects\Privat\GitlabManager\VSProject\GitlabManager\ViewModels\WindowMainVi
ewModel.cs:line 47

```

**Comment by xwipeoutx** [comment]
+1 I've run into the same problem
